### ISSUE TITLE
Typer Error problem

### ISSUE THREAD

**Issue by Voldemort112** [kongkx/homebridge-gree-air-conditioner#5]
**Hello! I get this error message after the first reboot!**

**Logs:
[2022. 05. 09. 13:44:37] Loading 2 platforms...
[2022. 05. 09. 13:44:37] [Config] Initializing config platform...
[2022. 05. 09. 13:44:37] [Config] Running in Service Mode
[2022. 05. 09. 13:44:37] [Gree AC] Initializing GreeAirConditioner platform...
[2022. 05. 09. 13:44:37] [Gree AC] Config: {"name":"Gree AC","port":7002,"scanCount":10,"language":"en","scanTimout":3000,"scanAddress":"192.168.1.69","defaultValue":{"minimumTargetTemperature":16,"maximumTargetTemperature":30,"sensorOffset":40,"defaultSpeed":4,"defaultVerticalSwing":0,"defaultHorizontalSwing":0,"statusUpdateInterval":3,"switches":"power,verticalSwing,horizontalSwing,quietMode,powerfulMode,light,dryMode,fanMode"},"devices":[{"sensorOffset":40,"defaultSpeed":3}],"platform":"GreeAirConditioner"}
[2022. 05. 09. 13:44:37] [Gree AC] Finished initializing platform: Gree AC
[2022. 05. 09. 13:44:37] [Gree AC] Loading accessory from cache: f4911eb7be94 undefined
[2022. 05. 09. 13:44:37] TypeError: Cannot read properties of undefined (reading 'mac')
    at GreePlatform.configureAccessory (C:\Users\admin\AppData\Roaming\npm\node_modules\homebridge-gree-air-conditioner\src\platform.ts:80:43)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\homebridge\src\bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (C:\Users\admin\AppData\Roaming\npm\node_modules\homebridge\src\bridgeService.ts:288:69)
    at Server.start (C:\Users\admin\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:173:24)
[2022. 05. 09. 13:44:37] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[2022. 05. 09. 13:44:42] [HB Supervisor] Restarting Homebridge...**

```
Show the Homebridge logs here, remove any sensitive information.
```

**{
    "bridge": {
        "name": "Homebridge 6992",
        "username": "****",
        "port": ***,
        "pin": "***",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Gree AC",
            "language": "en",
            "port": 7002,
            "scanAddress": "192.168.1.69",
            "defaultValue": {
                "statusUpdateInterval": 3,
                "sensorOffset": 40,
                "defaultSpeed": 4,
                "defaultVerticalSwing": 0,
                "defaultHorizontalSwing": 0
            },
            "devices": [
                {
                    "sensorOffset": 40,
                    "defaultSpeed": 3
                }
            ],
            "platform": "GreeAirConditioner"
        }
    ]
}**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **v1.2.0**:
* **Homebridge Version*v1.4.1*: 
* **Node.js Version*v14.17.0*: 
* **NPM Version**: 
* **Operating System*windows*:

**Comment by kongkx** [comment]
Maybe something wrong with the accessory cache.  I just publish an patch update to handle `undefined` accessory. You may give it a try.

And one more thing, your scanAddress should be  `192.168.1.255` instead of `192.168.1.69`.
